export const INJECTOR_EVENTS = {
  // farmon to injector
  LOOMA_EXPAND: "LOOMA_EXPAND",
  LOOMA_COLLAPSE: "LOOMA_COLLAPSE",
  START_COMPONENT_SELECTION: "START_COMPONENT_SELECTION",

  // injector to farmon
  LOOMA_STARTED: "LOOMA_STARTED",
  COMPONENT_SELECTED: "COMPONENT_SELECTED",
  UI_SNAPSHOT: "UI_SNAPSHOT",
} as const;
