import { SSE_EVENTS } from "../../schemas/index.js";

interface LogEvent {
  timestamp: string;

  type: EventType;

  data: unknown;
}

export interface CommandLog {
  id: string;

  type: "COMMAND" | "UNDO" | "REDO";
  status: "RUNNING" | "SUCCESS" | "FAILED";
  events: LogEvent[];

  createdAt: string;

  command?: string;

  completedAt?: string;

  error?: string;
}

export const LOG_EVENTS = {
  USER_COMMAND: "USER_COMMAND",
  COMMAND_RECEIVED: "COMMAND_RECEIVED",

  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_FAILED: "TASK_FAILED",

  QUERY_AGENT_PROMPT: "QUERY_AGENT_PROMPT",
  QUERY_AGENT_RESPONSE: "QUERY_AGENT_RESPONSE",
  PLANNER_PROMPT: "PLANNER_PROMPT",
  PLAN_GENERATED: "PLAN_GENERATED",
  PLANNER_RESPONSE: "PLANNER_RESPONSE",

  HEALTH_CHANGED: "HEALTH_CHANGED",

  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  COMPONENT_CONTEXT: "COMPONENT_CONTEXT",

  CHECKPOINT_CREATED: "CHECKPOINT_CREATED",
  CHECKPOINT_RESTORED: "CHECKPOINT_RESTORED",
  COMMAND_COMPLETED: "COMMAND_COMPLETED",
  ERROR: "ERROR",
} as const;

export const EVENTS = {
  ...LOG_EVENTS,
  ...SSE_EVENTS,
};

export const ERROR_CODES = {
  UNKNOWN_COMMAND: "UNKNOWN_COMMAND",

  COMPONENT_NOT_FOUND: "COMPONENT_NOT_FOUND",

  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_EXECUTION_FAILED: "TASK_EXECUTION_FAILED",
  TASK_ERROR: "TASK_ERROR",
  DIRECTORY_ALREADY_EXISTS: "DIRECTORY_ALREADY_EXISTS",
  COMPONENT_ALREADY_EXISTS: "COMPONENT_ALREADY_EXISTS",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  INVALID_COMPONENT: "INVALID_COMPONENT",
  CSS_NOT_FOUND: "CSS_NOT_FOUND",
  JSX_NOT_FOUND: "JSX_NOT_FOUND",
  TASK_VALIDATION_FAILED: "TASK_VALIDATION_FAILED",
  PAYLOAD_ERROR: "PAYLOAD_ERROR",

  PARSE_ERROR: "PARSE_ERROR",

  VALIDATION_FAILED: "VALIDATION_FAILED",

  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",

  FUNCTION_NOT_FOUND: "FUNCTION_NOT_FOUND",

  LLM_FAILED: "LLM_FAILED",

  LLM_INVALID_RESPONSE: "LLM_INVALID_RESPONSE",

  UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",

  INVALID_JSX: "INVALID_JSX",
  INVALID_PATH: "INVALID_PATH",

  UNDO_FAILED: "UNDO_FAILED",
  REDO_FAILED: "REDO_FAILED",
  ROLLBACK_FAILED: "ROLLBACK_FAILED",
  ROLLBACK_ERROR: "ROLLBACK_ERROR",

  QUERY_AGENT_FAILED: "QUERY_AGENT_FAILED",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type EventType = (typeof LOG_EVENTS)[keyof typeof LOG_EVENTS];
